name: Lint Code Base

on:
    push:
        branches: [feature/github-actions]

jobs: 
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn
            - name: Run unit tests
              run: yarn test:staged
    