name: Test code base

on:
    push:
        branches: [feature/github-actions]

jobs: 
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v3   
              with:
                node-version: '18'
                cache: 'yarn'
            - name: Install dependencies
              run: yarn
            - name: Run unit tests
              run: yarn test:staged 
    interaction-and-accessibility:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16.x'
        - name: Install dependencies
          run: yarn
        - name: Install Playwright
          run: npx playwright install --with-deps
        - name: Build Storybook
          run: yarn build-storybook --quiet
        - name: Serve Storybook and run tests
          run: |
            npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
              "npx http-server storybook-static --port 6006 --silent" \
              "npx wait-on tcp:6006 && yarn test-storybook"