name: Test code base

on:
    push:
        branches: [main]

jobs: 
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v3   
              with:
                node-version: '18'
                cache: 'yarn'
            - name: Install dependencies
              run: yarn
            - name: Run unit tests
              run: yarn test:staged 
    sb-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v3   
              with:
                node-version: '18'
                cache: 'yarn'
            - name: Install dependencies
              run: yarn
            - name: Storybook test-runner
              run: yarn build-storybook:ci
